version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    env_file: .env
    ports:
      - "4000:4000"
      - "5555:5555"

    volumes:
      - ../backend:/app
      - /app/node_modules

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - next_cache:/app/.next
      

volumes:
  postgres_data:
  next_cache:
