version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Porta padrão para acesso interno
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ../backend
    env_file: .env
    ports:
      - "4000:4000"
      - "5555:5555"  # Expondo a porta do Prisma Studio

    volumes:
      - ../backend:/app
      - /app/node_modules  # Evita sobrescrever os módulos dentro do container
    depends_on:
      postgres:
        condition: service_healthy  # Aguarda o banco estar pronto antes de iniciar

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
